spring.application.name=PROJ_M.C-Plasticos.ControleDeEstoque.v1.0
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:mem:bdMC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true